language: generic
# need super user permissions to execute this build
sudo: required
# need docker cli preinstalled
services: 
  - docker

# series of commands before tests are run
before_install:
  # better to use a tag instead of deal with id
  - docker build -t hexsoulb/docker-react-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true hexsoulb/docker-react-aws npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-aws"
  env: "Dockerreactaws-env"
  bucket_name: "elasticbeanstalk-us-west-2-875375255289"
  bucket_path: "docker-react-aws"
  edge: true
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"