version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      # Do not map a folder against app/node_modules in the container
      # Map the current folder outside the container to the app folder in the container
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - WATCHPACK_POLLING:true
  tests:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Do not map a folder against app/node_modules in the container
    # Map the current folder outside the container to the app folder in the container
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'run', 'test']
    environment:
      - CHOKIDAR_USEPOLLING:true